"""Add order field to Goal model

Revision ID: b96cf3d5ea53
Revises: 9cc5ae93eb2a
Create Date: 2024-11-21 13:12:54.272893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b96cf3d5ea53'
down_revision = '9cc5ae93eb2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goal', schema=None) as batch_op:
        batch_op.drop_column('order')

    # ### end Alembic commands ###
